export type AuthErrorCode =
  | 'INVALID_EMAIL'
  | 'INVALID_PASSWORD'
  | 'PASSWORD_TOO_WEAK'
  | 'INVALID_CREDENTIALS'
  | 'ACCOUNT_LOCKED'
  | 'EMAIL_NOT_VERIFIED'
  | 'SESSION_EXPIRED'
  | 'SESSION_INVALID'
  | 'EMAIL_EXISTS'
  | 'RATE_LIMIT_EXCEEDED'
  | 'INTERNAL_ERROR';
