// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class DnsRecord extends pulumi.CustomResource {
    /**
     * Get an existing DnsRecord resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DnsRecordState, opts?: pulumi.CustomResourceOptions): DnsRecord {
        return new DnsRecord(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'netlify:index/dnsRecord:DnsRecord';

    /**
     * Returns true if the given object is an instance of DnsRecord.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DnsRecord {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DnsRecord.__pulumiType;
    }

    declare public readonly flag: pulumi.Output<number>;
    /**
     * The hostname for the DNS record. For example, `www.example.com`.
     */
    declare public readonly hostname: pulumi.Output<string>;
    declare public /*out*/ readonly lastUpdated: pulumi.Output<string>;
    declare public readonly priority: pulumi.Output<number>;
    declare public readonly tag: pulumi.Output<string>;
    declare public readonly ttl: pulumi.Output<number>;
    /**
     * One of A, AAAA, ALIAS, CAA, CNAME, MX, NS, SPF, or TXT
     */
    declare public readonly type: pulumi.Output<string>;
    declare public readonly value: pulumi.Output<string>;
    declare public readonly zoneId: pulumi.Output<string>;

    /**
     * Create a DnsRecord resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DnsRecordArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DnsRecordArgs | DnsRecordState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DnsRecordState | undefined;
            resourceInputs["flag"] = state?.flag;
            resourceInputs["hostname"] = state?.hostname;
            resourceInputs["lastUpdated"] = state?.lastUpdated;
            resourceInputs["priority"] = state?.priority;
            resourceInputs["tag"] = state?.tag;
            resourceInputs["ttl"] = state?.ttl;
            resourceInputs["type"] = state?.type;
            resourceInputs["value"] = state?.value;
            resourceInputs["zoneId"] = state?.zoneId;
        } else {
            const args = argsOrState as DnsRecordArgs | undefined;
            if (args?.hostname === undefined && !opts.urn) {
                throw new Error("Missing required property 'hostname'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            if (args?.value === undefined && !opts.urn) {
                throw new Error("Missing required property 'value'");
            }
            if (args?.zoneId === undefined && !opts.urn) {
                throw new Error("Missing required property 'zoneId'");
            }
            resourceInputs["flag"] = args?.flag;
            resourceInputs["hostname"] = args?.hostname;
            resourceInputs["priority"] = args?.priority;
            resourceInputs["tag"] = args?.tag;
            resourceInputs["ttl"] = args?.ttl;
            resourceInputs["type"] = args?.type;
            resourceInputs["value"] = args?.value;
            resourceInputs["zoneId"] = args?.zoneId;
            resourceInputs["lastUpdated"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DnsRecord.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering DnsRecord resources.
 */
export interface DnsRecordState {
    flag?: pulumi.Input<number>;
    /**
     * The hostname for the DNS record. For example, `www.example.com`.
     */
    hostname?: pulumi.Input<string>;
    lastUpdated?: pulumi.Input<string>;
    priority?: pulumi.Input<number>;
    tag?: pulumi.Input<string>;
    ttl?: pulumi.Input<number>;
    /**
     * One of A, AAAA, ALIAS, CAA, CNAME, MX, NS, SPF, or TXT
     */
    type?: pulumi.Input<string>;
    value?: pulumi.Input<string>;
    zoneId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a DnsRecord resource.
 */
export interface DnsRecordArgs {
    flag?: pulumi.Input<number>;
    /**
     * The hostname for the DNS record. For example, `www.example.com`.
     */
    hostname: pulumi.Input<string>;
    priority?: pulumi.Input<number>;
    tag?: pulumi.Input<string>;
    ttl?: pulumi.Input<number>;
    /**
     * One of A, AAAA, ALIAS, CAA, CNAME, MX, NS, SPF, or TXT
     */
    type: pulumi.Input<string>;
    value: pulumi.Input<string>;
    zoneId: pulumi.Input<string>;
}
