// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class SiteBuildSettings extends pulumi.CustomResource {
    /**
     * Get an existing SiteBuildSettings resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SiteBuildSettingsState, opts?: pulumi.CustomResourceOptions): SiteBuildSettings {
        return new SiteBuildSettings(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'netlify:index/siteBuildSettings:SiteBuildSettings';

    /**
     * Returns true if the given object is an instance of SiteBuildSettings.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SiteBuildSettings {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SiteBuildSettings.__pulumiType;
    }

    declare public readonly baseDirectory: pulumi.Output<string>;
    declare public readonly branchDeployAllBranches: pulumi.Output<boolean>;
    declare public readonly branchDeployBranches: pulumi.Output<string[]>;
    declare public readonly buildCommand: pulumi.Output<string>;
    declare public readonly buildImage: pulumi.Output<string>;
    declare public readonly deployPreviews: pulumi.Output<boolean>;
    declare public readonly functionsDirectory: pulumi.Output<string>;
    declare public readonly functionsRegion: pulumi.Output<string>;
    declare public /*out*/ readonly lastUpdated: pulumi.Output<string>;
    declare public readonly packageDirectory: pulumi.Output<string>;
    declare public readonly prettyUrls: pulumi.Output<boolean>;
    /**
     * When enabled, prevents production deploys from sources other than the linked git repository.
     */
    declare public readonly preventNonGitProdDeploys: pulumi.Output<boolean>;
    declare public readonly productionBranch: pulumi.Output<string>;
    declare public readonly publishDirectory: pulumi.Output<string>;
    declare public readonly siteId: pulumi.Output<string>;
    declare public readonly stopBuilds: pulumi.Output<boolean>;
    /**
     * See more details in the<span pulumi-lang-nodejs=" netlify.WafPolicy " pulumi-lang-dotnet=" netlify.WafPolicy " pulumi-lang-go=" WafPolicy " pulumi-lang-python=" WafPolicy " pulumi-lang-yaml=" netlify.WafPolicy " pulumi-lang-java=" netlify.WafPolicy "> netlify.WafPolicy </span>resource.
     */
    declare public readonly wafPolicyId: pulumi.Output<string | undefined>;

    /**
     * Create a SiteBuildSettings resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SiteBuildSettingsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SiteBuildSettingsArgs | SiteBuildSettingsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SiteBuildSettingsState | undefined;
            resourceInputs["baseDirectory"] = state?.baseDirectory;
            resourceInputs["branchDeployAllBranches"] = state?.branchDeployAllBranches;
            resourceInputs["branchDeployBranches"] = state?.branchDeployBranches;
            resourceInputs["buildCommand"] = state?.buildCommand;
            resourceInputs["buildImage"] = state?.buildImage;
            resourceInputs["deployPreviews"] = state?.deployPreviews;
            resourceInputs["functionsDirectory"] = state?.functionsDirectory;
            resourceInputs["functionsRegion"] = state?.functionsRegion;
            resourceInputs["lastUpdated"] = state?.lastUpdated;
            resourceInputs["packageDirectory"] = state?.packageDirectory;
            resourceInputs["prettyUrls"] = state?.prettyUrls;
            resourceInputs["preventNonGitProdDeploys"] = state?.preventNonGitProdDeploys;
            resourceInputs["productionBranch"] = state?.productionBranch;
            resourceInputs["publishDirectory"] = state?.publishDirectory;
            resourceInputs["siteId"] = state?.siteId;
            resourceInputs["stopBuilds"] = state?.stopBuilds;
            resourceInputs["wafPolicyId"] = state?.wafPolicyId;
        } else {
            const args = argsOrState as SiteBuildSettingsArgs | undefined;
            if (args?.buildCommand === undefined && !opts.urn) {
                throw new Error("Missing required property 'buildCommand'");
            }
            if (args?.productionBranch === undefined && !opts.urn) {
                throw new Error("Missing required property 'productionBranch'");
            }
            if (args?.publishDirectory === undefined && !opts.urn) {
                throw new Error("Missing required property 'publishDirectory'");
            }
            if (args?.siteId === undefined && !opts.urn) {
                throw new Error("Missing required property 'siteId'");
            }
            resourceInputs["baseDirectory"] = args?.baseDirectory;
            resourceInputs["branchDeployAllBranches"] = args?.branchDeployAllBranches;
            resourceInputs["branchDeployBranches"] = args?.branchDeployBranches;
            resourceInputs["buildCommand"] = args?.buildCommand;
            resourceInputs["buildImage"] = args?.buildImage;
            resourceInputs["deployPreviews"] = args?.deployPreviews;
            resourceInputs["functionsDirectory"] = args?.functionsDirectory;
            resourceInputs["functionsRegion"] = args?.functionsRegion;
            resourceInputs["packageDirectory"] = args?.packageDirectory;
            resourceInputs["prettyUrls"] = args?.prettyUrls;
            resourceInputs["preventNonGitProdDeploys"] = args?.preventNonGitProdDeploys;
            resourceInputs["productionBranch"] = args?.productionBranch;
            resourceInputs["publishDirectory"] = args?.publishDirectory;
            resourceInputs["siteId"] = args?.siteId;
            resourceInputs["stopBuilds"] = args?.stopBuilds;
            resourceInputs["wafPolicyId"] = args?.wafPolicyId;
            resourceInputs["lastUpdated"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SiteBuildSettings.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering SiteBuildSettings resources.
 */
export interface SiteBuildSettingsState {
    baseDirectory?: pulumi.Input<string>;
    branchDeployAllBranches?: pulumi.Input<boolean>;
    branchDeployBranches?: pulumi.Input<pulumi.Input<string>[]>;
    buildCommand?: pulumi.Input<string>;
    buildImage?: pulumi.Input<string>;
    deployPreviews?: pulumi.Input<boolean>;
    functionsDirectory?: pulumi.Input<string>;
    functionsRegion?: pulumi.Input<string>;
    lastUpdated?: pulumi.Input<string>;
    packageDirectory?: pulumi.Input<string>;
    prettyUrls?: pulumi.Input<boolean>;
    /**
     * When enabled, prevents production deploys from sources other than the linked git repository.
     */
    preventNonGitProdDeploys?: pulumi.Input<boolean>;
    productionBranch?: pulumi.Input<string>;
    publishDirectory?: pulumi.Input<string>;
    siteId?: pulumi.Input<string>;
    stopBuilds?: pulumi.Input<boolean>;
    /**
     * See more details in the<span pulumi-lang-nodejs=" netlify.WafPolicy " pulumi-lang-dotnet=" netlify.WafPolicy " pulumi-lang-go=" WafPolicy " pulumi-lang-python=" WafPolicy " pulumi-lang-yaml=" netlify.WafPolicy " pulumi-lang-java=" netlify.WafPolicy "> netlify.WafPolicy </span>resource.
     */
    wafPolicyId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a SiteBuildSettings resource.
 */
export interface SiteBuildSettingsArgs {
    baseDirectory?: pulumi.Input<string>;
    branchDeployAllBranches?: pulumi.Input<boolean>;
    branchDeployBranches?: pulumi.Input<pulumi.Input<string>[]>;
    buildCommand: pulumi.Input<string>;
    buildImage?: pulumi.Input<string>;
    deployPreviews?: pulumi.Input<boolean>;
    functionsDirectory?: pulumi.Input<string>;
    functionsRegion?: pulumi.Input<string>;
    packageDirectory?: pulumi.Input<string>;
    prettyUrls?: pulumi.Input<boolean>;
    /**
     * When enabled, prevents production deploys from sources other than the linked git repository.
     */
    preventNonGitProdDeploys?: pulumi.Input<boolean>;
    productionBranch: pulumi.Input<string>;
    publishDirectory: pulumi.Input<string>;
    siteId: pulumi.Input<string>;
    stopBuilds?: pulumi.Input<boolean>;
    /**
     * See more details in the<span pulumi-lang-nodejs=" netlify.WafPolicy " pulumi-lang-dotnet=" netlify.WafPolicy " pulumi-lang-go=" WafPolicy " pulumi-lang-python=" WafPolicy " pulumi-lang-yaml=" netlify.WafPolicy " pulumi-lang-java=" netlify.WafPolicy "> netlify.WafPolicy </span>resource.
     */
    wafPolicyId?: pulumi.Input<string>;
}
